### PR TITLE
Add unit tests to restbuilder

### PR DESCRIPTION
**Pull request by jackburridge**
I've added some simple unit tests to the restbuilder. There are a few things of note:
1. I've configured tox to support py35, py36, py37, and py38. py39 could be added
2. I've used ``assert_doc_equal`` instead of exact comparison, mainly because changes to the writer may effect whitespace but may not change the actual document

### CODE REVIEW

**Comment by macfreek** [comment]
Hi @jackburridge, thanks a lot for this PR. It was something that was indeed missing.

I really like that this PR is atomic. As such I'm happy to merge it.

I haven't gotten a change to run it yet, but have a few comments based on a quick code review

* Let's support Python 3.5-3.9 for now. 3.5 is no longer maintained, but Sphinx still supports it too (it will be dropped in Sphinx 4.0). Could you add 3.9 to `tox.ini`? It should also be changed in the `README.rst` (which still lists 3.4), but I prefer to do that in a separate commit, so it is very clear that Python 2.7 and 3.4 support is dropped.
* Should `tox.ini` also need a dependency on the `sphinx` and/or `docutils` packages (next to `pytest`)?
* `assert_doc_equal` seems like a valid approach? Would `assert_doc_equal` also declare two documents equal if the changes are different than whitespace (e.g. a bullet list with `-` or `+` as bullets)?
* Please add yourself to `CONTRIBUTORS.txt` using your preferred attribution.

**Comment by jackburridge** [comment]
Hi @macfreek,

* `tox.ini` doesn't require the `sphinx` dependencies, as it installs the package from the `setup.py`
* `assert_doc_equal` does work on docs if there are changes different from whitespace, for example:
    ```rst
    This is **bold**.
    ```
    is the same as:
    ```rst
    This is :strong:`bold`.
    ```

**Comment by jackburridge** [comment]
On a side note, the one thing I've found `assert_doc_equal` doesn't work perfectly on is tables

**Comment by macfreek** [comment]
Thanks a lot for your contribution.

I am happy to take more tests. In particular I'd love a test for URLs that also test for the alt, tag and uri parameters, as this would give me confidence to merge some downstream forks (#3 comment:643761271 of 14 Jun 2020)

**Comment by jackburridge** [comment]
@macfreek  is it worth raising a general issue for basic unit tests?

**Comment by macfreek** [comment]
> @macfreek is it worth raising a general issue for basic unit tests?

If you like, please do. That said, I prefer pull requests over issues.
If might give the URI tests a shot, but it unfortunately will be beyond some other things on my pile, so if you or someone else beats me to it -- all the better.

But feel free to contribute in any way you see fit. Either tables, URI, Travis or other CI/CD integrations -- whatever you feel is useful.

**Comment by macfreek** [comment]
@jackburridge I have two questions about Github workflows and tox, and so far haven't found a good answer online. Feel free to weigh in if you have any advice (or not).

1. I struggling to avoid duplicating information in both [`.github/workflows/tests.yml`](https://github.com/sphinx-contrib/restbuilder/blob/master/.github/workflows/tests.yml) and [`tox.ini`](https://github.com/sphinx-contrib/restbuilder/blob/master/tox.ini). I have configured [`tox.ini` to run on a matrix of multiple Sphinx versions and multiple Python versions](https://github.com/sphinx-contrib/restbuilder/blob/ba65eb81da4b2934025b1efb2ff67f24db0b1c3e/tox.ini). This works will if `tox` is run on the command line, but this is ignored by the workflow. So I seem to have to replicate this matrix there too. Do you happen to know a way to avoid repeating information over two files (in your original contribution, the different Python versions to test were also included in both files, so I wonder if this duplication of information is always there).

2. In your contribution, you added the directories `tests/datasets/common` and `tests/expected/common`. I didn't really think this thought, but why the `common` subdirectory? I assumed it is to distinguish between e.g. common reStructuredText directives, and directives which are specific to Sphinx. At least, that's how I use it now. If you have other suggestions, let me know.

**Comment by jackburridge** [comment]
@macfreek 
1. Yeah I think you'll always have that duplication, but the more you add to the `tox.ini` you should end up with a lower percentage of duplication in the long run.
2. I took the layout ideas from the [confluencebuilder](https://github.com/sphinx-contrib/confluencebuilder) project. The advantage of having sub-directories would be you be able to more easily test directives such as toctree's as they could be more easily isolated.

**Comment by macfreek** [comment]
@jackburridge Thanks.
With the last commit, both `tox` and the Github workflow have a test matrix that tests the code against a matrix of different Sphinx versions (1.4 to 3.4) and Python version (3.5 to 3.9). So I'm very pleased with that.

Regretfully, github workflows ignores the `tox.ini` envlist, and `tox` does not have knowledge about github workflows. Hence, I don't see an easy way around the duplication, even considering tools like [tox-gh-actions](https://github.com/ymyzk/tox-gh-actions). I put a note in the config files warning about the duplication, and leave it at that for now.

The good news is that I already caught a few errors, so the tests do what they're supposed to do. Thanks for getting `restbuilder` in this state.

**Pull request merged**
