### PR TITLE
Add action to run tox

### PR DESCRIPTION
**Pull request by jackburridge**
This has been tested against my own fork https://github.com/jackburridge/restbuilder/pull/1

### CODE REVIEW

**Comment by macfreek** [comment]
Thanks! I'm currently mostly using gitlab, and my previous github experience was with a `.travis.yml` file. So thanks for showing me a modern approach here too.

I have one question, looking at the code: what is the reason for using `tox`? According to `tox.ini`, all that `tox` does is to call pytest.

Why not simply have an action that calls pytest directly in `.github/workflows/build.yml`, as the example in [the documentation](https://docs.github.com/en/actions/guides/building-and-testing-python):

    - name: Test with pytest
      run: pytest

I've seen this tox → pytest approach before, so it is not uncommon. I'm merely curious about the considerations to use this approach.

**Comment by jackburridge** [comment]
I would use `tox` mainly because its slightly DRYer, meaning any test configuration changes will only need to happen in `tox.init`.

**Comment by macfreek** [comment]
I usually prefer the less levels of indirection, but this works too. I love that it works in #15.

One last question: if we were to add other tests later (for example `flake8` for formatting or `mypy` for type checking), would that be a separate job in the workflow description, or would that go in tox.ini config? (I guess both are possible, I'm asking about what you think is best practice)

**Comment by jackburridge** [comment]
> I usually prefer the less levels of indirection, but this works too. I love that it works in #15.
> 
> One last question: if we were to add other tests later (for example `flake8` for formatting or `mypy` for type checking), would that be a separate job in the workflow description, or would that go in tox.ini config? (I guess both are possible, I'm asking about what you think is best practice)


You could add `flake8` and/or `mypy` to tox. My preference is to add mypy and linters to [pre-commit](https://pre-commit.com/) then also run that in CI. As you say though it is a level of indirection, but view it also as a test running the testing tools a developer should be using.

**Comment by macfreek** [comment]
A short summary of what I would feel is important (mostly as a reminder for myself, for lack of other places to put it):
* I like to add tests not only for different Python versions, but also different Sphinx versions
* I like to add a flake8 linter test at some point in time. I'm on the fence about adding a `.pre-commit-config.yaml` file. Most people will not have installed pre-commit, so it's a bit moot. It doesn't really hurt, but it is yet another place with configuration settings (next to `tox.ini`). I would rather see an advice that people run `tox` themselves before submitting code.
* I have no plans on adding type checks myself at the moment, but since Sphinx has type checking these days, and usually find it beneficial, I would accept a PR that adds it.

**Pull request merged**
